import assert from 'node:assert/strict';
process.env.APP_PASSWORD='test-password';process.env.BCO_API_KEY='bco-api-test';process.env.APP_CONFIRM_SECRET='confirm-test';process.env.APP_SESSION_SECRET='session-test';process.env.CRON_SECRET='cron-test';
process.env.META_PAGE_TOKEN='legacy-fve-token';process.env.META_PAGE_ID='117';
const lib=await import('../api/_lib.js');
const conf=await import('../api/_confirm.js');
const meta=await import('../api/_meta-config.js');
const healthHandler=(await import('../api/health.js')).default;
const autopilot=(await import('../api/autopilot.js')).default;
const token=lib.createSessionToken();assert.equal(lib.verifySessionToken(token),true);assert.equal(lib.verifySessionToken(token+'x'),false);
const payload={project:'jihoceske',message:'test'},ct=conf.createConfirmation('meta:publish',payload);assert.equal(conf.verifyConfirmation(ct,'meta:publish',payload),true);assert.throws(()=>conf.verifyConfirmation(ct,'meta:publish',{...payload,project:'mazliprint'}));
assert.equal(meta.metaConfig('jihoceske').configured,true);assert.equal(meta.metaConfig('mazliprint').configured,false);assert.throws(()=>lib.projectKey('evil'));
const fakeReq={headers:{cookie:`bc_session=${encodeURIComponent(token)}`}};assert.equal(lib.auth(fakeReq),true);
const noCookie={headers:{'x-app-key':'test-password'}};assert.equal(lib.auth(noCookie),true);
const oldPassword=process.env.APP_PASSWORD;delete process.env.APP_PASSWORD;
assert.equal(lib.auth({headers:{'x-app-key':'bco-api-test'}}),true);
assert.equal(lib.auth({headers:{'x-app-key':'wrong'}}),false);
process.env.APP_PASSWORD=oldPassword;
const healthResponse=()=>{let status=200,body;return{setHeader(){},statusCode:200,status(n){status=n;return this},json(v){body=v;return this},get result(){return{status,body}}}};
const protectedHealth=healthResponse();healthHandler({headers:{authorization:'Bearer cron-test'}},protectedHealth);assert.equal(protectedHealth.result.status,200);assert.equal(protectedHealth.result.body.ok,true);
const deniedHealth=healthResponse();healthHandler({headers:{}},deniedHealth);assert.equal(deniedHealth.result.status,401);
const oldKvUrl=process.env.KV_REST_API_URL,oldKvToken=process.env.KV_REST_API_TOKEN;
delete process.env.KV_REST_API_URL;delete process.env.KV_REST_API_TOKEN;
const autopilotResponse=healthResponse();await autopilot({method:'POST',headers:{authorization:'Bearer cron-test'}},autopilotResponse);assert.equal(autopilotResponse.result.status,503);assert.equal(autopilotResponse.result.body.error,'KV_NOT_CONFIGURED');
if(oldKvUrl!==undefined)process.env.KV_REST_API_URL=oldKvUrl;if(oldKvToken!==undefined)process.env.KV_REST_API_TOKEN=oldKvToken;
const fs=await import('node:fs/promises');
const app=await fs.readFile('public/app.js','utf8');
for(const marker of ['state.project!==runProject','app_snapshots','leadScore','RECOVERY_KEY','dailyBrief','recordActivity','startEditLead','leadToComms','scheduleDraftSave','maybeAutoRecovery','renderPortfolio','MEDIA_THUMB_CACHE','IntersectionObserver','ensureMediaFile','clearThumbCache','useFallbackFiles','generateReel','publishReel','renderMetaConnection','generateCampaign','leadFollowKit','autoSelectReelPhotos','truthGuard','pipelineStats','renderSales','quoteSave','dealCoachRun','JOB_TEMPLATES','createJob','renderCashWatch','buildReelPreview','exportReelStoryboard','maybeDueNotification','requestPersistentStorage','runContentWorker','renderWorker','lastContentWorker'])assert.ok(app.includes(marker),marker);
const html=await fs.readFile('public/index.html','utf8');
for(const marker of ['Business Control ONE 17 MAX','id="todayFocus"','id="recoveryList"','id="portfolioSummary"','id="mediaLocalSearch"','id="reels"','id="reelStoryboard"','id="reelPhone"','id="sales"','id="salesQueue"','id="quoteList"','id="jobs"','id="jobBoard"','id="cashWatch"','id="enableNotifications"','id="control"','id="controlQueue"','id="controlProjects"','id="worker"','id="workerRun"','id="workerQueue"'])assert.ok(html.includes(marker),marker);
const sw=await fs.readFile('public/sw.js','utf8');assert.ok(sw.includes('bc17-crm-live-v1'));assert.ok(sw.includes("url.pathname.startsWith('/api/')"));assert.ok(sw.includes('notificationclick'));
const session=await fs.readFile('api/session.js','utf8');assert.ok(session.includes('MAX_ATTEMPTS=8'));assert.ok(session.includes('LOCK_MS=3*60*1000'));assert.ok(session.includes('Retry-After'));
const health=await fs.readFile('api/health.js','utf8');assert.ok(health.includes("version:'17-max'"));assert.ok(health.includes('if(!healthAuth(req))return noauth(res);'));assert.ok(health.includes('req.headers?.authorization'));
const ai=await fs.readFile('api/ai.js','utf8');assert.ok(ai.includes("task==='salescoach'"));assert.ok(ai.includes("task==='quote'"));
const comms=await fs.readFile('api/comms.js','utf8');assert.ok(comms.includes('PROJECT_MISMATCH'));
const rcs=await fs.readFile('api/_comms.js','utf8');assert.ok(rcs.includes('RCS_USE_GLOBAL_ENDPOINT'));
const autopilotSource=await fs.readFile('api/autopilot.js','utf8');assert.ok(autopilotSource.includes("KV_NOT_CONFIGURED"));
console.log('SMOKE OK — 17 MAX auth, BCO_API_KEY bridge, project isolation, Control Room, Sales Command, Quote Builder, Delivery OS, Reels Composer 3, cloud sync and mobile-safe media.');

assert(html.includes('id="metaCenterText"') && html.includes('id="metaCopyDiag"'));
assert(app.includes('function renderMetaCenter') && app.includes('function metaDiagnostic'));
assert.ok(app.includes("theme:'nrsm'") && app.includes('function applyWorkspace'));
assert.ok(html.includes('id="workspaceName"') && html.includes('id="workspaceSignature"') && html.includes('workspace-switcher'));