import { randomUUID } from 'node:crypto';
import { env, kvSetNxEx, fetchJsonWithRetry } from './_lib.js';

const ORG='d2751286-da99-42c0-b8ac-6a2da8ecdabf';
const SB_URL=env('SUPABASE_URL','https://vjzzvopwecmwuccdidzq.supabase.co');
const HUNTER='https://api.hunter.io/v2';
const clean=(v,max=1000)=>String(v??'').trim().slice(0,max);
function sbKey(){const key=env('SUPABASE_SERVICE_ROLE_KEY')||env('SUPABASE_SERVICE_KEY');if(!key)throw Object.assign(new Error('SUPABASE_SERVICE_ROLE_KEY_NOT_CONFIGURED'),{status:503});return key;}
async function sb(path,params={},method='GET',payload){const key=sbKey(),u=new URL(`${SB_URL}/rest/v1/${path}`);for(const[k,v]of Object.entries(params))u.searchParams.set(k,String(v));return fetchJsonWithRetry(u,{method,headers:{apikey:key,Authorization:`Bearer ${key}`,'content-type':'application/json',Prefer:'return=representation'},...(payload===undefined?{}:{body:JSON.stringify(payload)})},2);}
async function hunter(path,query={}){const key=env('HUNTER_API_KEY');if(!key)throw Object.assign(new Error('HUNTER_API_KEY_NOT_CONFIGURED'),{status:503});const u=new URL(`${HUNTER}${path}`);u.searchParams.set('api_key',key);for(const[k,v]of Object.entries(query))if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v));return fetchJsonWithRetry(u,{},2);}
function fit(c,e={}){let s=40,t=`${c.industry||''} ${c.category||''} ${c.description||''}`.toLowerCase();for(const k of ['music','festival','club','bar','fashion','streetwear','record','label','merch','artist','dj','gaming','community'])if(t.includes(k))s+=6;if(e.position)s+=5;if(e.seniority==='executive')s+=10;if(e.verification?.status==='valid')s+=10;return Math.min(100,s);}
async function createDraft(prospect){const key=env('GEMINI_API_KEY');if(!key)return null;const prompt=`Napiš stručnou první B2B zprávu v češtině pro potenciálního partnera NŘŠM. Nabídni krátký merch návrh na míru. Neuváděj vymyšlené reference, ceny, čísla ani existující vztah. Vrať pouze JSON {"subject":"","body":""}. Firma: ${clean(prospect.company_name,220)}; kontakt: ${clean(prospect.contact_name,160)}; pozice: ${clean(prospect.metadata?.position,160)}; doména: ${clean(prospect.domain,220)}.`;const j=await fetchJsonWithRetry(`https://generativelanguage.googleapis.com/v1beta/models/${env('GEMINI_MODEL','gemini-3.5-flash-lite')}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{maxOutputTokens:450}})},1);const text=j.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||'';try{const m=text.match(/\{[\s\S]*\}/);return JSON.parse(m?m[0]:text);}catch{return text?{subject:'NŘŠM — merch návrh na míru',body:text.trim()}:null;}}
export default async function handler(req,res){const secret=env('CRON_SECRET');if(!secret)return res.status(503).json({error:'CRON_SECRET_NOT_SET'});if(req.headers.authorization!==`Bearer ${secret}`)return res.status(401).json({error:'UNAUTHORIZED'});const lock=await kvSetNxEx('business-control:merch-cron-lock',randomUUID(),300);if(!lock)return res.status(409).json({error:'ALREADY_RUNNING'});try{const enabled=env('MERCH_AUTO_PROSPECTING','true')==='true';if(!enabled)return res.json({ok:true,skipped:'MERCH_AUTO_PROSPECTING_DISABLED'});const queries=String(env('MERCH_DISCOVERY_QUERIES','DnB techno neuro music clubs and festivals in Czech Republic|Czech streetwear brands and independent fashion labels|Czech DJs artists event promoters and music communities')).split('|').map(clean).filter(Boolean).slice(0,3);const created=[];for(const q of queries){const j=await hunter('/discover',{query:q,limit:5});for(const c of (Array.isArray(j.data)?j.data:[]).slice(0,5)){if(!c.domain)continue;let ds;try{ds=await hunter('/domain-search',{domain:clean(c.domain,253),limit:1,seniority:'executive,senior',department:'marketing,management,sales,communication'});}catch{continue;}const e=Array.isArray(ds.data?.emails)?ds.data.emails[0]:null;if(!e||!e.value||e.verification?.status!=='valid')continue;const email=clean(e.value,320).toLowerCase();const existing=await sb('merch_prospects',{organization_id:`eq.${ORG}`,email:`eq.${encodeURIComponent(email)}`,select:'id,status',limit:1});if(existing?.[0]?.status==='suppressed')continue;const row={organization_id:ORG,company_name:clean(c.company||c.name||c.organization,240)||null,domain:clean(c.domain,253).toLowerCase(),contact_name:[e.first_name,e.last_name].filter(Boolean).join(' ')||null,email,phone:clean(e.phone_number,80)||null,source:'hunter-auto',source_url:j.meta?.permalink||null,fit_score:fit(c,e),status:'qualified',notes:e.position?`Pozice: ${e.position}`:null,metadata:{industry:c.industry||c.category||null,position:e.position||null,seniority:e.seniority||null,department:e.department||null,email_confidence:e.confidence??null,verification:e.verification?.status||null,auto_discovered:true}};const saved=await sb('merch_prospects',{on_conflict:'organization_id,email'},'POST',row);const p=Array.isArray(saved)?saved[0]:saved;if(!p)continue;const draft=await createDraft(p);if(draft?.body){await sb('merch_outreach_drafts',{},'POST',{organization_id:ORG,prospect_id:p.id,channel:'email',subject:clean(draft.subject,998)||'NŘŠM — merch návrh na míru',body:clean(draft.body,12000),personalization:{generated_by:'merch-cron',approval_required:true},status:'draft'});}created.push({id:p.id,company:p.company_name,contact:p.contact_name,email:p.email});}}
return res.json({ok:true,processed:created.length,created,at:new Date().toISOString()});}catch(e){console.error('MERCH_CRON_ERROR',String(e?.message||e));return res.status(Number(e?.status)||500).json({error:e?.message||'MERCH_CRON_FAILED'});}}
